## Numpy Random Module
* rand : Random values in a given shape.
* randn : Return a sample(or samples) from the "standard normal" distribution.
* randint : Return random integers from low (inclusive) to high(exclusive).
* random : Return random floats in the half-open interval[0.0,1.0)
* choice : Generates a random sample from a given 1-D array.
* shuffle : Shuffles the contents of a sequence

In [3]:
import numpy as np
a = np.arange(10)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [5]:
a_plus_5 = np.arange(10)+5
print(a_plus_5)
print(type(a_plus_5))

[ 5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [6]:
np.random?

### random shuffling of array

In [8]:
np.random.shuffle(a)
print(a)

[6 3 0 8 9 2 5 4 7 1]


### Generating array of numbers

In [9]:
a = np.random.rand(2,3)
print(a)

[[0.35333891 0.27141806 0.83473871]
 [0.02333899 0.76302931 0.71096348]]


### Generating array from nirmal ditribution

In [11]:
a = np.random.randn(2,3)
print(a)

[[-0.48747821  1.12789699 -1.37872116]
 [ 0.22505685  2.05561012  0.81242886]]


In [16]:
np.random.randn?

### getting particular amount of numbers in a particular range

In [21]:
a = np.random.randint(5,10,3)
a

array([7, 6, 6])

### Randomly picking an element

In [22]:
element = np.random.choice([1,4,3,2,11,27])
print(element)

1


In [25]:
np.random.random()

0.5759499616636331

### Seed in random
* If you want your radom number must be generated in same order every time you use seed(decides the starting number).
* These random numbers are **pseudo random generator**

In [26]:
np.random.seed(1)