In [1]:
import pandas as pd
import numpy as np

In [15]:
my_data = pd.read_csv("Marks.csv",dtype=int)

### Droping multiple columns 

In [18]:
my_data = my_data.drop(columns =["Unnamed: 0","MarksA"])

KeyError: "['Unnamed: 0' 'MarksA'] not found in axis"

In [19]:
my_data.describe()

MarksB     MarksC     MarksD
count   5.000000   5.000000   5.000000
mean   65.400000  48.800000  57.000000
std    38.246568  31.324112  36.366193
min     3.000000  14.000000  17.000000
25%    55.000000  28.000000  19.000000
50%    85.000000  42.000000  71.000000
75%    87.000000  68.000000  88.000000
max    97.000000  92.000000  90.000000

### Last certain columns|

In [20]:
my_data.tail()

MarksB  MarksC  MarksD
0      55      68      71
1      97      14      88
2      85      92      19
3       3      28      17
4      87      42      90

### Accessing a particular row

In [26]:
my_data.iloc[3]

MarksB     3
MarksC    28
MarksD    17
Name: 3, dtype: int32

### Accessing a particular row and column

In [27]:
my_data.iloc[3,1]

28

In [28]:
idx = my_data.columns.get_loc("MarksB")
my_data.iloc[3,idx]

3

### Accessing a particular row and column when you don't know the location

In [31]:
idx = [my_data.columns.get_loc("MarksB"),my_data.columns.get_loc("MarksC")]
print("idx: ",idx)
my_data.iloc[3,idx]

idx:  [0, 1]


MarksB     3
MarksC    28
Name: 3, dtype: int32

In [33]:
my_data.iloc[:3,[1,2]]

MarksC  MarksD
0      68      71
1      14      88
2      92      19

In [35]:
my_data.sort_values(by=["MarksB"],ascending=True)

MarksB  MarksC  MarksD
3       3      28      17
0      55      68      71
2      85      92      19
4      87      42      90
1      97      14      88

### Doubt

In [36]:
my_data.sort_values(by=["MarksB","MarksC"],ascending=True)

MarksB  MarksC  MarksD
3       3      28      17
0      55      68      71
2      85      92      19
4      87      42      90
1      97      14      88

In [38]:
data_array = my_data.values

In [40]:
print(type(my_data))
print(my_data.shape)

<class 'pandas.core.frame.DataFrame'>
(5, 3)


In [41]:
print(data_array)
print(type(data_array))

[[55 68 71]
 [97 14 88]
 [85 92 19]
 [ 3 28 17]
 [87 42 90]]
<class 'numpy.ndarray'>


In [42]:
data_array[2][2]

19

### Making a Pandas DataFrame from a numpy array

In [44]:
new_df = pd.DataFrame(data_array,dtype=np.int32,columns=["Physics","Chemistry","Maths"])

In [54]:
new_df

Physics  Chemistry  Maths
0       55         68     71
1       97         14     88
2       85         92     19
3        3         28     17
4       87         42     90

### Will not store index numbers

In [57]:
# Will not store index numbers
new_df.to_csv("PCM.csv",index=False)

In [58]:
PCM = pd.read_csv("PCM.csv")
print(PCM)

   Physics  Chemistry  Maths
0       55         68     71
1       97         14     88
2       85         92     19
3        3         28     17
4       87         42     90
